// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaeqzmsxcpnrnbwccrzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZXF6bXN4Y3Bucm5id2NjcnpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDI3NDAsImV4cCI6MjA2MzU3ODc0MH0.qsdmaq6_zqDnubD5w-xQRAMuvmxj-pc41T6w0NEBLec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});